import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
	variable: "--font-geist-sans",
	subsets: ["latin"],
});

const geistMono = Geist_Mono({
	variable: "--font-geist-mono",
	subsets: ["latin"],
});

export const metadata: Metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html
			lang="en"
			className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}
		>
			<body className="min-h-full flex flex-col bg-amber-50">
				{/* corners */}
				<p className="text-[3vh] absolute z-99 top-[2vh] left-[2vw] hand-coffe">
					2026
				</p>

				<a
					href="/all-nav"
					className="text-[3vh] absolute z-99 top-[2vh] right-[2vw] hand-coffe"
				>
					All Nav
				</a>

				<p className="text-[3vh] absolute z-99 bottom-[2vh] right-[2vw] hand-coffe">
					by Jane
				</p>
				{children}
			</body>
		</html>
	);
}
